version: '3.4'

x-default:
  &default-bot
  restart:
    always
  build:
    context: .
  volumes:
    - ./resources/questions.yaml:/opt/app/resources/questions.yaml:ro
  depends_on:
    - tests

services:
  tests:
    restart:
      "no"
    build:
      context: .
      dockerfile: tests.Dockerfile
      args:
        BUILD_ENV: TEST

  rudeboy_bot:
    <<: *default-bot
    env_file: [.env]
